server:
  port: 8081
spring:  
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: "jdbc:h2:mem:productDb;DB_CLOSE_DELAY=-1"
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        ddl-auto: create-drop
eureka:
  instance:    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    metadata-map:      zone : A  client:
    register-with-eureka: true
    fetch-registry: true    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
